### ISSUE TITLE
Hello!I am confused about the process of data processing...

### ISSUE THREAD

**Issue by sakaili** [wintersummer01/deepJSCC#1]
In your code， you process the CIFAR-10 dataset in the following ways. 
Could you please tell me why it should be processed in the following way: 
1. Why do you need to add to a total of six dimensions? 
2. Why do you need to swap the dimensions of the dataset?

Thanks!
```
def getTrainDataset(root, show_spec=False):
    dataset = []
    for i in range(5):
        with open(root + f'/data_batch_{i+1}', 'rb') as fo:
            dict = pickle.load(fo, encoding='bytes')
            dataset.append(np.reshape(dict[b'data'], (-1, 3, 32, 32)).transpose((0, 2, 3, 1)))
    dataset = np.vstack(dataset)

    if DATA_TYPE == 'CIFAR-10':
        dataset = dataset[0:int(dataset.shape[0]/SQRT_BATCH_SIZE**2)*SQRT_BATCH_SIZE**2]
        dataset = np.reshape(dataset, (-1, SQRT_BATCH_SIZE, SQRT_BATCH_SIZE, 32, 32, 3))
        dataset = np.transpose(dataset, (0, 1, 3, 2, 4, 5))
        dataset = np.reshape(dataset, (-1, 1, 32*SQRT_BATCH_SIZE, 32*SQRT_BATCH_SIZE, 3))
        
    if show_spec:
        print('length of dataset: ', len(dataset))
        print('dataset image shape:', dataset[0][0].shape)
        print('example image:')
        plt.imshow(dataset[0][0])
        plt.show()
    
    return tf.data.Dataset.from_tensor_slices(tf.cast(dataset, tf.float32)), dataset[0][0].shape
```

**Comment by wintersummer01** [comment]
From batch size 64, it is common to use the dataset with shapes of (64, 32, 32, 3), which is (B, H, W, C). 
But instead of having a dataset like this, I wanted to concatenate 64 images, 8 in a column and 8 in a row.
Which gives the data with the shape of (1, 256, 256, 3).

The code where reshape -> transpose -> reshape changes the image (64, 32, 32, 3) into (1, 256, 256, 32), 
but instead of just reshaping, this kind of code gives images with well-aligned.

Please note that the image dimension is 5, (not 6 !) which is for
(num_batches, batch_size, height, width, channel)

**Comment by sakaili** [comment]
Thank you very much!!
