### ISSUE TITLE
Question about train.py

### ISSUE THREAD

**Issue by sakaili** [wintersummer01/deepJSCC#2]
Hi! I'm sorry to bother you again.In the train.py:
1.Why `k = np.prod(shape)*bw`, and also what's the shape of the variant `shape`?
In the model.py:
1.Why can filter be calculated like this`filter = k*2/((shape[0]/4)**2)`
Since I need to port the code to pytorch, and your repo doesn't have the relevant files for the dataset, it's hard for me to know these details by running your code. I'm very sorry to bother you again and hope to get a reply!

**Comment by wintersummer01** [comment]
1. Shape is returned from the file utils.datasets, which is tuple (256, 256, 3). It is a transformed (concatenated) shape of CIFAR dataset with batch size 64. (you asked in former issue)

2. The encoder encodes the input image R^n into symbol C^k, and the bandwidth is n/k. Thus the output of the encoder should be 2k real values, And that is how we calculate the number of filters to get 2k values in result.

**Comment by sakaili** [comment]
Thanks for your answer！Wondering if you could upload the dataset used by the code, thank you very much!

**Comment by wintersummer01** [comment]
Thank you for your interest. 
The used dataset is CIFAR10, but it is hard to upload on the repo because of its memory and copyright. 
You can easily find CIFAR10 on the website below, please use the Python version.
https://www.cs.toronto.edu/~kriz/cifar.html

Also, please note that my code is not official and is not written for education. 
It's only for my own interest and studying Semantic Communication.
So there would be some errors and problems. 
Thank you.

**Comment by sakaili** [comment]
OK, I will try it!  :)
